name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.requires_python }}
  - pip

  # Base conda deps
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - pytest
  - pytest-cov

  # This project conda deps

  - pip:
    # Base pip deps: Docs
    - mkdocs
    - mkdocs-material
    - mkdocs-minify-plugin
    - pygments
    - pymdown-extensions

    # This project pip deps
    - python-coveralls
