name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.requires_python }}
  - pip

  # Development conda deps
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel
  - pytest
  - pytest-cov

  # Other development deps

  - pip:
    # This project pip deps

    # Development docs deps
    - mkdocs
    - mkdocs-material
    - mkdocs-minify-plugin
    - pygments
    - pymdown-extensions
