name: {{ cookiecutter.project_name }}
channels:
  - conda-forge
dependencies:
  - python={{ cookiecutter.requires_python }}
  - pip

  # Dev tools
  - setuptools
  - setuptools_scm
  - pylint
  - flake8
  - black
  - isort
  - twine
  - wheel

  # Package deps

  # Testing
  - pytest
  - pytest-cov

  - pip:
    # Docs
    - mkdocs
    - mkdocs-material
    - mkdocs-minify-plugin
    - pygments
    - pymdown-extensions
